//
//  text_strings.h
//  TreeCrafter
//
//  Created by SIMON WINDER on 7/25/13.
//  Copyright (c) 2013 Impressive Machines LLC. All rights reserved.
//

#ifndef TreeCrafter_text_strings_h
#define TreeCrafter_text_strings_h


#define NSLS_TREE                   NSLocalizedString(@"tree", @"Just the word for a tree - lower case noun")
#define NSLS_ANGLE_MODE             NSLocalizedString(@"Angle Mode", @"Title for control to set the branching angle pattern of the tree")
#define NSLS_INTERVALS              NSLocalizedString(@"Intervals", @"A label for a control that relates to a division of the length of a tree branch into parts")
#define NSLS_COMPLEXITY             NSLocalizedString(@"Complexity", @"Title for control to the level of complexity of the branch pattern of the tree")
#define NSLS_LEVEL_OF_DETAIL        NSLocalizedString(@"Level of Detail", @"Title for control to select how much detail is shown")
#define NSLS_DETAIL                 NSLocalizedString(@"Detail", @"A label for a control that selects how much detail is shown")
#define NSLS_APEX_LENGTH            NSLocalizedString(@"Apex Length", @"Title for control to set the length of the top branches of the tree")
#define NSLS_LENGTH                 NSLocalizedString(@"Length", @"A label that indicates how long something is - short word")
#define NSLS_LENGTHS                NSLocalizedString(@"Lengths", @"A label that refers to the lengths of branches on the tree - short word")
#define NSLS_TRUNK_WIDTH            NSLocalizedString(@"Trunk Width", @"Title for control to set the width of the tree trunk")
#define NSLS_WIDTH                  NSLocalizedString(@"Width", @"A label that indicates how wide something is - short word")
#define NSLS_RANDOM_WIGGLE          NSLocalizedString(@"Random Wiggle", @"Title for control to make the branches deviate randomly away from being straight")
#define NSLS_WIGGLE                 NSLocalizedString(@"Wiggle", @"Title for control to make the branches deviate randomly away from being straight")
#define NSLS_RANDOM_ANGLES          NSLocalizedString(@"Random Angles", @"Title for control to make the branches sprout at random angles")
#define NSLS_ANGLES                 NSLocalizedString(@"Angles", @"A label for that indicates that the user can change tree branching angles")
#define NSLS_RANDOM_LENGTHS         NSLocalizedString(@"Random Lengths", @"Title for control to make the branches grow to different random lengths")
#define NSLS_TRUNK_TAPER            NSLocalizedString(@"Trunk Taper", @"Title for control to set how fast the tree trunk gets thinner towards the top")
#define NSLS_TAPER                  NSLocalizedString(@"Taper", @"A label for a control to set how fast the tree trunk gets thinner towards the top - short word")
#define NSLS_APEX_MODE              NSLocalizedString(@"Apex Mode", @"Title for control to set what the top branches of the tree look like")
#define NSLS_RANDOM_INTERVALS       NSLocalizedString(@"Random Intervals", @"Title for control to make the tree branches sprout at various random positions along the trunk")
#define NSLS_TRUNK_COLOR            NSLocalizedString(@"Trunk Color", @"Title for control to set the color of the tree trunk")
#define NSLS_LEAF_COLOR             NSLocalizedString(@"Leaf Color", @"Title for control to set the color of the leaves of the tree")
#define NSLS_BACKGROUND_COLOR       NSLocalizedString(@"Background Color", @"Title for control to set the background color of the tree")
#define NSLS_GRADIENT_SATURATION    NSLocalizedString(@"Gradient Saturation", @"Title for control to change how much of the leaf color is present for the color gradient")
#define NSLS_SATURATION             NSLocalizedString(@"Saturation", @"Title for control to change how much of the leaf color is present for the color gradient - use a short word")
#define NSLS_GRADIENT_SHARPNESS     NSLocalizedString(@"Gradient Sharpness", @"Title for control to change how sharp the spatial color transition is on the tree")
#define NSLS_SHARPNESS              NSLocalizedString(@"Sharpness", @"Title for control to change how sharp the spatial color transition is on the tree - use a short word")
#define NSLS_GRADIENT               NSLocalizedString(@"Gradient", @"A title for the controls that affect the spatial distribution of colors")
#define NSLS_BRANCHES_PER_NODE      NSLocalizedString(@"Branches Per Node", @"Title for control to set the number of tree branches coming from each sprouting point")
#define NSLS_BRANCHES               NSLocalizedString(@"Branches", @"Refers to the branches of a tree - short word")
#define NSLS_BRANCH_NODES           NSLocalizedString(@"Branch Nodes", @"Title for control to set the number of nodes which branches can sprout from")
#define NSLS_NODES                  NSLocalizedString(@"Nodes", @"Title for control to set the number of nodes which branches can sprout from")
#define NSLS_WIND_RATE              NSLocalizedString(@"Wind Rate", @"Title for control to set the speed for the wind animation")
#define NSLS_WIND_DEPTH             NSLocalizedString(@"Wind Depth", @"Title for control to set how intense the tree shakes for the wind animation")
#define NSLS_WIND                   NSLocalizedString(@"Wind", @"A title for the controls which alter the wind animation parameters")
#define NSLS_SPREAD_ANIMATION       NSLocalizedString(@"Spread Animation", @"Title for control to set the animation parameters for spreading of the tree branches")
#define NSLS_SPREAD                 NSLocalizedString(@"Spread", @"Title for control to set how much the shape of the tree spreads out")
#define NSLS_BEND_ANIMATION         NSLocalizedString(@"Bend Animation", @"Title for control to set the animation parameters for the bending of the tree trunk")
#define NSLS_BEND                   NSLocalizedString(@"Bend", @"Title for control to set how much the trunk and branches of the tree are curved")
#define NSLS_SPIN_ANIMATION         NSLocalizedString(@"Spin Animation", @"Title for control to set the animation parameters for the rotation of the tree about its axis")
#define NSLS_SPIN                   NSLocalizedString(@"Spin", @"Title for control to change the rotation of the tree about its axis")
#define NSLS_TWIST_ANIMATION        NSLocalizedString(@"Twist Animation", @"Title for control to set the animation parameters for the twist of the tree like a corkscrew")
#define NSLS_TWIST                  NSLocalizedString(@"Twist", @"Title for control to change the twist of the tree like a corkscrew")
#define NSLS_GROWTH_ANIMATION       NSLocalizedString(@"Growth Animation", @"Title for control to set the animation parameters for the amount the tree has grown")
#define NSLS_GROWTH                 NSLocalizedString(@"Growth", @"Title for control to change the amount that the tree has grown")
#define NSLS_DELAY_ANIMATION        NSLocalizedString(@"Delay Animation", @"Title for control to set the animation parameters for the growth delay for the lowest branches")
#define NSLS_DELAY                  NSLocalizedString(@"Delay", @"Title for control to set the growth delay for the lowest branches")
#define NSLS_GEORATIO_ANIMATION     NSLocalizedString(@"Georatio Animation", @"Title for control to change the animaiton parameters for the geometric ratio of the branching pattern")
#define NSLS_GEORATIO               NSLocalizedString(@"Georatio", @"Title for control to set the geometric ratio of the branching pattern")
#define NSLS_GEOMETRIC_RATIO        NSLocalizedString(@"Geometric Ratio", @"Title for control to set the geometric ratio of the branching pattern")
#define NSLS_ASPECT_RATIO_ANIMATION NSLocalizedString(@"Aspect Ratio Animation", @"Title for control set the animation parameters for the width to height ratio of the tree")
#define NSLS_ASPECT_RATIO           NSLocalizedString(@"Aspect Ratio", @"Title for control to change the width to height ratio of the tree")
#define NSLS_ASPECT                 NSLocalizedString(@"Aspect", @"Title for control to change the width to height ratio of the tree - use a short word")
#define NSLS_BALANCE_ANIMATION      NSLocalizedString(@"Balance Animation", @"Title for control to set the animation parameters for the left-right angle balance of the tree")
#define NSLS_BALANCE                NSLocalizedString(@"Balance", @"Title for control to adjust the left-right angle balance of the tree")
#define NSLS_SYMMETRY_ANIMATION     NSLocalizedString(@"Symmetry Animation", @"Title for control to set the animation parameters for the left-right growth symmetry of the tree")
#define NSLS_SYMMETRY               NSLocalizedString(@"Symmetry", @"Title for control to adjust the left-right growth symmetry of the tree")
#define NSLS_TREE_MODE              NSLocalizedString(@"Tree Mode", @"Title for control to change the overall structure of the tree")
#define NSLS_ANIMATION              NSLocalizedString(@"Animation", @"Title for control to turn on and off the animation effects")
#define NSLS_ON_OFF                 NSLocalizedString(@"On / Off", @"A label for a switch that can be on or off")
#define NSLS_DEPTH                  NSLocalizedString(@"Depth", @"A label for a control that changes the intensity of an effect - use a short word")
#define NSLS_RATE                   NSLocalizedString(@"Rate", @"A label for a control that changes the animation speed of an effect - use a short word")
#define NSLS_VALUE                  NSLocalizedString(@"Value", @"A label for various sliders that control the value of a tree parameter")
#define NSLS_LEAF                   NSLocalizedString(@"Leaf", @"A label for a control that refers to the leaves of the tree")
#define NSLS_TRUNK                  NSLocalizedString(@"Trunk", @"A label for a control that refers to the main trunk of the tree")
#define NSLS_BACKGROUND             NSLocalizedString(@"Background", @"A label for a control that refers to the background of the tree drawing")
#define NSLS_REFRESH                NSLocalizedString(@"Refresh", @"A label for a button that re-generates a new set of random parameters")
#define NSLS_SHAPE                  NSLocalizedString(@"Shape", @"A label that refers to the shape of the tree")
#define NSLS_BRANCHING              NSLocalizedString(@"Branching", @"A label that refers to the branching structure of the tree")
#define NSLS_SIZES                  NSLocalizedString(@"Sizes", @"A label that refers to various size-setting parameters for the tree")
#define NSLS_APEX                   NSLocalizedString(@"Apex", @"A label that refers to the top of the tree")
#define NSLS_RANDOMIZE              NSLocalizedString(@"Randomize", @"A label that refers to the a set of parameters that control how chaotic the tree looks")
#define NSLS_CREATED_USING__        NSLocalizedString(@"Created using Tree Crafter for iPad", @"Text to say this app was used to make an image")
#define NSLS_TOUCH_TO_MOVE__        NSLocalizedString(@"Touch to move and scale", @"Touch the screen - instructions about interacting with the tree size and position")
#define NSLS_SAVE_VIDEO             NSLocalizedString(@"Save Video", @"Title for dialog to allow saving a video")
#define NSLS_15_SEC                 NSLocalizedString(@"15 sec", @"Short menu item indicating the number of seconds")
#define NSLS_30_SEC                 NSLocalizedString(@"30 sec", @"Short menu item indicating the number of seconds")
#define NSLS_1_MIN                  NSLocalizedString(@"1 min", @"Short menu item indicating the number of minutes")
#define NSLS_2_MIN                  NSLocalizedString(@"2 min", @"Short menu item indicating the number of minutes")
#define NSLS_5_MIN                  NSLocalizedString(@"5 min", @"Short menu item indicating the number of minutes")
#define NSLS_CHOOSE_VIDEO_DURATION  NSLocalizedString(@"Choose Video Duration", @"Title for menu that allows the length of video to be selected")
#define NSLS_SAVING_VIDEO__         NSLocalizedString(@"Saving Video to Camera Roll", @"Message to say we are saving the video")
#define NSLS_UNABLE_TO_SAVE_VIDEO   NSLocalizedString(@"Unable to Save Video", @"Title for error dialog")
#define NSLS_EITHER_CAMERA__        NSLocalizedString(@"Either camera-roll access is disabled, or another condition is preventing the saving of videos. Camera-roll access can be enabled via your device's privacy settings.", @"Error message")
#define NSLS_EITHER_CAMERA__2       NSLocalizedString(@"Either camera-roll access is disabled, or some other condition is preventing the processing of images. Camera-roll access can be enabled via your device's privacy settings.", @"Message in error dialog")
#define NSLS_OK                     NSLocalizedString(@"OK", @"OK button used to dismiss dialog boxes")
#define NSLS_TARGETS                NSLocalizedString(@"Targets", @"A title for the set of tree paramteres that can be animated")
#define NSLS_COLORS                 NSLocalizedString(@"Colors", @"A title for the controls that change the tree color")
#define NSLS_PORTRAIT               NSLocalizedString(@"Portrait", @"Indicates that paper is in portrait mode, ie tall and narrow")
#define NSLS_LANDSCAPE              NSLocalizedString(@"Landscape", @"Indicates that paper is in landscape mode, ie wider than it is tall")
#define NSLS_NORMAL                 NSLocalizedString(@"Normal", @"Label to indicate that we are using the normal image resolution")
#define NSLS_HIGH_DETAIL            NSLocalizedString(@"High Detail", @"Label to indicate that we are using high resolution drawing")
#define NSLS_HEADER_MESSAGE         NSLocalizedString(@"Header Message", @"Placeholder for whatever message the user wants for a title on the image")
#define NSLS_FOOTER_MESSAGE         NSLocalizedString(@"Footer Message", @"Placeholder for whatever message the user wants for a footer on the image")
#define NSLS_BACKGOUND_IMAGE        NSLocalizedString(@"Background Image", @"Label on a button that allows selection of the background image to use")
#define NSLS_TEXT_COLOR             NSLocalizedString(@"Text Color", @"Label on a button that allows selection of the text color to use")
#define NSLS_ADD                    NSLocalizedString(@"Add", @"Label on a button that allows adding of a background image")
#define NSLS_REMOVE                 NSLocalizedString(@"Remove", @"Label on a button that allows removing of a background image")
#define NSLS_SAVE_IMAGE             NSLocalizedString(@"Save Image", @"Title for a menu that is used for saving images to the camera roll")
#define NSLS_CANCEL                 NSLocalizedString(@"Cancel", @"Label for button that is used to cancel an operation")
#define NSLS_DONE                   NSLocalizedString(@"Done", @"Label for button that user hits when they are finished changing some setting");
#define NSLS_EDIT                   NSLocalizedString(@"Edit", @"Label for button that is used to enable editing")
#define NSLS_SAVING_IMAGE__         NSLocalizedString(@"Saving Image to Camera Roll", @"Title for a dialog box that shows that we are currently saving an image")
#define NSLS_PREPARING_IMAGE        NSLocalizedString(@"Preparing Image", @"Title for a dialog box that shows that we are getting an image ready to share")
#define NSLS_UNABLE_TO_PROCESS__    NSLocalizedString(@"Unable to Process Image", @"Title for error dialog")
#define NSLS_MAIL_UNAVAILABLE       NSLocalizedString(@"Mail Unavailable", @"Error message when sending mail does not work")
#define NSLS_THIS_DEVICE_MAY__      NSLocalizedString(@"This device may not be configured to send email.", @"Explanation of mail sending error")
#define NSLS_CHECK_OUT_MY__         NSLocalizedString(@"Check out my latest masterpiece", @"Message to place in subject line when sending user created tree by email")
#define NSLS_TWITTER__              NSLocalizedString(@"Twitter Unavailable", @"Error message when we can't connect to Twitter")
#define NSLS_THIS_DEVICE__T         NSLocalizedString(@"This device is not currently able to post to Twitter.", @"Explanation of error message")
#define NSLS_FACEBOOK__             NSLocalizedString(@"Facebook Unavailable", @"Error message when we can't connect to Facebook")
#define NSLS_THIS_DEVICE__F         NSLocalizedString(@"This device is not currently able to post to Facebook.", @"Explanation of error message")
#define NSLS_SINA_WEIBO__           NSLocalizedString(@"Sina Weibo Unavailable", @"Error message when we can't connect to Sina Weibo")
#define NSLS_THIS_DEVICE__S         NSLocalizedString(@"This device is not currently able to post to Sina Weibo.", @"Explanation of error message")
#define NSLS_SAVE_TREE              NSLocalizedString(@"Save Tree", @"Label for button that is used to save the user's tree")
#define NSLS_CHOOSE_PAPER_SIZE      NSLocalizedString(@"Choose Paper Size", @"Title for control that allows the user to set the paper size")
#define NSLS_POSTCARD__             NSLocalizedString(@"Postcard (4.25 \u00D7 6 in)", @"Title for paper that is postcard size")
#define NSLS_LETTER__               NSLocalizedString(@"Letter (8.5 \u00D7 11 in)", @"Title for paper that is letter size")
#define NSLS_POSTER__1              NSLocalizedString(@"Poster (11 \u00D7 17 in)", @"Title for paper that is poster size")
#define NSLS_POSTER__2              NSLocalizedString(@"Poster (18 \u00D7 24 in)", @"Title for paper that is poster size")
#define NSLS_POSTER__3              NSLocalizedString(@"Poster (24 \u00D7 36 in)", @"Title for paper that is poster size")
#define NSLS_BACKGROUND_FILL        NSLocalizedString(@"Background Fill", @"Label for switch to make the background opaque when on, transparent when off")
//#define NSLS_LINE_WEIGHT__1         NSLocalizedString(@"Line Weight (1.00 \u00D7)", @"Label that indicates how thick the lines are in the drawing")
#define NSLS_LINE_WEIGHT__2         NSLocalizedString(@"Line Weight (%@ \u00D7)", @"Label that indicates how thick the lines are in the drawing")
#define NSLS_SAVE_PDF_FILE          NSLocalizedString(@"Save PDF File", @"Title for dialog to help user save tree as a PDF file")
#define NSLS_PDF_ORGANIZER          NSLocalizedString(@"PDF Organizer", @"Title for menu showing previously saved PDF files")
#define NSLS_PREPARING_PDF_FILE     NSLocalizedString(@"Preparing PDF File", @"Title for dialog showing progress of saving a PDF")
#define NSLS_UNABLE_TO_SAVE_PDF__   NSLocalizedString(@"Unable to Save PDF File", @"Title for error dialog")
#define NSLS_AN_UNEXPECTED__        NSLocalizedString(@"An unexpected condition is preventing the completion of this operation.", @"Error message")
#define NSLS_USE_ONE_FINGER__       NSLocalizedString(@"Use one finger to pan around.", @"Instruction for how to use the panning touch gestures")
#define NSLS_USE_TWO_FINGERS__      NSLocalizedString(@"Use two fingers to zoom in and out.", @"Instruction for how to use the zoom touch gestures")
#define NSLS_TURNING_WITH_TWO__     NSLocalizedString(@"Turning with two fingers bends the tree.", @"Instruction for how to use touch gestures to make the tree trunk appear curved one way or the other")
#define NSLS_MOVING_TWO_FINGERS__   NSLocalizedString(@"Moving two fingers together controls the shape.", @"Instruction for how to use the touch gestures for changing the shape of the tree")
#define NSLS__HELPMESSAGE1          NSLocalizedString(@"Start by using the Shape Menu to change the appearance of your tree. You can begin from any tree, including those in the Saved Trees menu.", @"Help info")
#define NSLS__HELPMESSAGE2          NSLocalizedString(@"Once you have a good shape, you can experiment with the colors using the Color Settings Menu.", @"Help info")
#define NSLS__HELPMESSAGE3          NSLocalizedString(@"Create all sorts of mesmerizing motion effects using the Animation Menu. To avoid confusion, turn off animation when you first edit the shape.", @"Help info")
#define NSLS__HELPMESSAGE4          NSLocalizedString(@"The Saved Trees Menu allows you to save and organize your work. Example trees are provided to encourage your creative spirit.", @"Help info")
#define NSLS__HELPMESSAGE5          NSLocalizedString(@"You can share your trees in various ways and save images or video to the camera roll. You can even export your trees as PDFs to incorporate into art work.", @"Help info")
#define NSLS_TOUCH_CONTROLS         NSLocalizedString(@"Touch Controls", @"Title for help menu")
#define NSLS_USAGE_GUIDE            NSLocalizedString(@"Usage Guide", @"Title for help menu")
#define NSLS_START_HERE             NSLocalizedString(@"Start Here", @"Speech bubble to tell the user where to go first")
#define NSLS_MB                     NSLocalizedString(@"MB", @"Megabytes")
#define NSLS_KB                     NSLocalizedString(@"KB", @"Kilobytes")
#define NSLS_A6__                   NSLocalizedString(@"A6 (105 \u00D7 148 mm)", @"Paper size")
#define NSLS_A5__                   NSLocalizedString(@"A5 (148 \u00D7 210 mm)", @"Paper size")
#define NSLS_A4__                   NSLocalizedString(@"A4 (210 \u00D7 297 mm)", @"Paper size")
#define NSLS_A3__                   NSLocalizedString(@"A3 (297 \u00D7 420 mm)", @"Paper size")
#define NSLS_A2__                   NSLocalizedString(@"A2 (420 \u00D7 594 mm)", @"Paper size")
#define NSLS_A1__                   NSLocalizedString(@"A1 (594 \u00D7 841 mm)", @"Paper size")

#endif
